# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ pkgs, modulesPath, ... }:

{
  # Enable ZSH
  programs.zsh.enable = true;

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users.ronald = {
    shell = pkgs.zsh;
    isNormalUser = true;
    description = "Ronald van Kouwen";
    extraGroups = [ "wheel" ];
    hashedPassword = "$6$Iv6NWzA.rVjoD0PS$FuW/U6J4fhEGsaMLbkRjoBZJoy6HPAUG8eajpHsiskkM9KEnturay11X5rbgFUncH.Mr0johepUvuJzbOsh.u.";
    packages = with pkgs; [];
  };

  # Zabbix server
  services.phpfpm.pools.zabbix.phpPackage = pkgs.php83;
  services.zabbixServer.enable = true;

  services.zabbixWeb = {
    enable = true;
    httpd.virtualHost = {
      hostName = "zabbix.bttf.lan";
      adminAddr = "webmaster@bttf.lan";
    };
  };

  # Add a zabbix client on the server
  services.zabbixAgent = {
    enable = true;
    server = "localhost";
  };



  # Enable the Flakes feature and the accompanying new nix command-line tool
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  # Package installation 
  environment.systemPackages = with pkgs; [
    vim # Do not forget to add an editor to edit configuration.nix! The Nano editor is also installed by default.
    git
    zabbix.agent
    zabbix.server
  ];

  imports = [
    # Include the default incus configuration.
    "${modulesPath}/virtualisation/incus-virtual-machine.nix"
    # Include the container-specific autogenerated configuration.
    ./incus.nix
  ];

  networking = {
    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;
  };

  systemd.network = {
    enable = true;
    networks."50-enp5s0" = {
      matchConfig.Name = "enp5s0";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };
  
  # Enable the OpenSSH daemon.
  services.openssh.enable = true;
  services.openssh.settings.PasswordAuthentication = false;

  # Disabe password authentication for wheel group
  security.sudo.wheelNeedsPassword = false;

  # Allow zabbix traffic
  networking.firewall.enable = true;
  networking.firewall.allowedTCPPorts = [ 22 80 443 10051 10050 ];

  # networking.firewall.allowedTCPPorts = [ 8096 ];
  system.stateVersion = "25.11"; # Did you read the comment?
}
