# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ pkgs, modulesPath, ... }:

{
  # Enable ZSH
  programs.zsh.enable = true;

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users.ronald = {
    shell = pkgs.zsh;
    isNormalUser = true;
    description = "Ronald van Kouwen";
    extraGroups = [ "wheel" ];
    packages = with pkgs; [];
  };

  # Enable the Flakes feature and the accompanying new nix command-line tool
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  services.jellyfin = {
    enable = true;
    openFirewall = true;
  };
  
  environment.systemPackages = with pkgs; [
    vim # Do not forget to add an editor to edit configuration.nix! The Nano editor is also installed by default.
    git
    jellyfin
    jellyfin-web
    jellyfin-ffmpeg
  ];

  imports = [
    # Include the default incus configuration.
    "${modulesPath}/virtualisation/incus-virtual-machine.nix"
    # Include the container-specific autogenerated configuration.
    ./incus.nix
  ];

  networking = {
    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;
  };

  systemd.network = {
    enable = true;
    networks."50-enp5s0" = {
      matchConfig.Name = "enp5s0";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };
  
  # Enable the OpenSSH daemon.
  services.openssh.enable = true;
  services.openssh.settings.PasswordAuthentication = false;

###########################################################
 fileSystems."/mnt/ronald" = {
   device = "//10.10.10.3/ronald";
   fsType = "cifs";
   options = [ "credentials=/root/.ronald" "x-systemd.automount" "auto" "uid=996" "gid=995" "file_mode=0700" "dir_mode=0700" ];
 };

 fileSystems."/mnt/debbie" = {
   device = "//10.10.10.3/debbie";
   fsType = "cifs";
   options = [ "credentials=/root/.debbie" "x-systemd.automount" "auto" "uid=996" "gid=995" "file_mode=0700" "dir_mode=0700" ];
 };
##########################################################

  # Disabe password authentication for wheel group
  security.sudo.wheelNeedsPassword = false;

  # networking.firewall.allowedTCPPorts = [ 8096 ];
  system.stateVersion = "25.11"; # Did you read the comment?
}
